### ISSUE TITLE
Weird screen glitch

### ISSUE THREAD

**Issue by TheReddest339** [Sildurs-shaders/sildurs-shaders.github.io#4] opened 2019-07-12 15:41 UTC
I was having fun for a while with the shader pack, everything working, until I notice this happening:
![image](https://user-images.githubusercontent.com/52831497/61140695-ca3bb780-a4c3-11e9-87bc-13cbea635296.png)
![image](https://user-images.githubusercontent.com/52831497/61140707-d32c8900-a4c3-11e9-8df1-bcf3aa8ef9cd.png)

**Comment by TheReddest339** [comment] 2019-07-12 15:41
Can I please know what I'm doing wrong? I tried restarting Minecraft, still not working.

**Comment by Sildurs-shaders** [comment] 2019-07-12 22:18
Known issue on vega gpus, caused by bad opengl drivers by amd. Latest working driver was 18.6.1, not sure if it's fixed in the very latest driver version.

**Closed** 2019-07-17 03:07 UTC
