### ISSUE TITLE
invalid program "composite"

### ISSUE THREAD

**Issue by xzTWINzx** [Sildurs-shaders/sildurs-shaders.github.io#161] opened 2021-08-03 18:22 UTC
on versions 1.29 extra and extra VL in version 1.16.5, when teleporting to the lower world, everything is black for me . and in the chat when teleporting, the following appears: "invalid program "composite"".
![2021-08-03_21 20 19](https://user-images.githubusercontent.com/88400050/128066430-41a4a580-e307-414a-a869-13bc15f37971.png)
![2021-08-03_21 19 54](https://user-images.githubusercontent.com/88400050/128066434-344b3fc1-a85a-4bac-a212-b654d205fbbd.png)
![2021-08-03_21 20 15](https://user-images.githubusercontent.com/88400050/128066437-95d1a344-d305-4292-952f-3dbf3dc08f43.png)
![2021-08-03_21 20 22](https://user-images.githubusercontent.com/88400050/128066444-85f8f139-aeb1-4507-aeed-9b1e2d1c82e2.png)
![2021-08-03_21 20 25](https://user-images.githubusercontent.com/88400050/128066447-7caba485-648a-4262-9b36-1be930e77291.png)

**Comment by Sildurs-shaders** [comment] 2021-09-19 09:19
Fixed in upcoming version, caused by TAA.

**Closed by Sildurs-shaders** 2021-09-19 09:19 UTC
